### PR TITLE
Added a new netstandard 2.0 library to support NetCore

### PR DESCRIPTION
**Pull request by raffaeler**
There are no changes to the sources. The pull request is long because I moved the sources to a "shared project" in order to reuse the same sources in both the desktop (original) library and in the new "netstandard 2.0" library.
The effective changes are:
1. Moved the sources in a shared project
2. Created a new netstandard 2.0 library
3. Referenced the sources from both the desktop and netstandard libraries
4. Added NUnit as a nuget package
5. Added ".vs" folder in gitignore

An additional step would be to create a nuspec for the netstandard library and add it to nuget.

HTH,
Raf

### CODE REVIEW

**Comment by samuelventura** [comment]
I will be needing more time to setup VS to test this. I am using SharpDevelop exclusively right now. Thank you for sharing.

**Comment by raffaeler** [comment]
Got it.
If you want to test it, please use VS2017 (with the latest update 3). The community edition would be perfectly fine. By installing just the .NET / NET Core related stuff, it should be a very fast setup.
It should also work with VSCode, but I didn't try it.

**Comment by samuelventura** [comment]
I'm looking into this and I think there is a way to support netstandard2.0 without moving any code around. I will try that approach first and will let you know when ready. Please try it out and see if it fits your need. Thank you.

**Comment by raffaeler** [comment]
Yes, it is definitely possible but netstandard libraries will require a .NET Framework (classic) application to depend on several nuget packages that before they didn't depend on.
This is the reason why I suggested you to create both the desktop and nestandard libraries with a single codebase.
If instead those dependencies are not a problem for you, go on with just nestandard.

**Comment by samuelventura** [comment]
A couple of hours ago I released and published to nuget version 1.0.6 that includes support for net40 and netstandard2.0. That release was tested to work on MacOS/Ubuntu (.Net Core 2.0.2) and Windows 10 (both SharpDevelop NetFramework40 target and .Net Core 2.0.2). I found the vscode/dotnetCLI development approach refreshing (thanks for the pointers there) compared to the monster VS2017 is. Not to mention that being able to develop from my MacBookPro got me sold. An added benefit is that the project and configuration files are significantly reduced. I will be leaving this PR open for a while to hear your feedback on this release.  Thank you.

**Pull request closed without merging**
